apiVersion: apps/v1
kind: Deployment
metadata:
  name: devchitchat-web
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devchitchat-web
  replicas: 1
  template:
    metadata:
      labels:
        app: devchitchat-web
    spec:
      containers:
      - name: devchitchat-web
        image: local/devchitchat-web:0.1.2
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: DB_PATH
          value: "/var/lib/devchitchat/chat.db"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: sqlite-data
          mountPath: /var/lib/devchitchat
      volumes:
      - name: sqlite-data
        persistentVolumeClaim:
          claimName: devchitchat-web-sqlite
---
apiVersion: v1
kind: Service
metadata:
  name: devchitchat-web-service
spec:
  selector:
    app: devchitchat-web
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devchitchat-web-sqlite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
